version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    assignees:
      - yamatt
    labels:
      - dependabot
      - github-actions
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - yamatt
    labels:
      - dependabot
      - python
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - yamatt
    labels:
      - dependabot
      - docker
